### ISSUE TITLE
我用这个项目开发,对接html的静态代码, 发现ajax请求要跨域很麻烦,请问怎么配置比较好

### ISSUE THREAD

**Issue by ithjz** [lihengming/spring-boot-api-project-seed#103]
我用这个项目开发,对接html的静态代码, 发现ajax请求要跨域很麻烦,请问怎么配置比较好

Failed to load http://192.168.3.14:8080/user/detail: No 'Access-Control-Allow-Origin' header is present on the requested resource.
 Origin 'http://192.168.3.14:8718' is therefore not allowed access.

**Comment by wang-y** [comment]
@Override
public void addCorsMappings(CorsRegistry registry) {
    registry.addMapping("/**");
}
