### ISSUE TITLE
修改项目名称BASE_PACKAGE = "com.bolang.clw" 后运行有问题

### ISSUE THREAD

**Issue by delphishen** [lihengming/spring-boot-api-project-seed#104]
Error:(6, 27) java: 程序包com.bolang.clw.core不存在
Error:(18, 43) java: 找不到符号
  符号: 类 AbstractService

这些类都默认在com.company.project 里面。还需要修改哪里的配置

**Comment by lihengming** [comment]
com.company.project  也需要手工改成 com.bolang.clw.
