### ISSUE TITLE
Thks and a suggestion

### ISSUE THREAD

**Issue by zorkeAccount** [lihengming/spring-boot-api-project-seed#109]
（1）感谢：首先十分感谢大神的分享，解决了现在公司内部spring + mybatis大量代码的编写工作量，在此我也在公司曾经推广过使用mybatis-generator插件实现一些代码的自动创建，但是还是不够简洁而且并没有能够对service和controller层进行模板化创建代码；而某一天看到你的这个开源项目，眼睛一亮，这不是就是自己一直code过程中的痛点嘛-相当于以mybatis为基础，不仅实现了springboot-JPA的功能，也对service和controller利用freemarker进行生成，简直完美！！既解决了mybatis大量基本增删改查的代码的“冗余”，也能够很好地自主去写一些复杂查询的SQL，可以说是JPA在mybatis层面的完美应用加模板扩展；
（2）应用：在对楼主原有的代码进一步定制化和一些特定的改造之后，同时封装了一些其他的小工具如dbdeploy实现对表结构和数据的管理友好化，在自己的努力下自己二次封装的一套工具代码目前已经在公司基于Spring SpringMVC和Spring boot的多个项目中得到应用；
（3）建议：经过在多个项目的实际使用过程中，尤其是多人开发的过程中，还有一个痛点就是数据库表结构可能不同的开发人员会适当地根据自己的业务需要去做一些表结构或初始化数据的更改（JPA已可以自动根据Java类去构建表），然后我们在实际使用的过程中采用的是一个小工具dbdeploy-ant-3.0M3.jar + maven进行管理的，希望楼主可以在该项目中集成dbdeploy以更方便同学们！当然，可能楼主本来就已经有一些非常好的工具了，我这边仅是浅薄的见解只供小小的建议，烦请多多交流和指点！
（4）贡献：也正是楼主的无私奉献，才能够解决我这类小菜菜鸟的code痛点，我也一并将自己封装的其他工具开源给了社区，谢谢！

**Comment by lihengming** [comment]
谢谢，很高兴这个小项目能够帮助到你哈，最近比较忙，等有空我看下dbdeploy哈，开源让世界更美好哈 :)

**Comment by lihengming** [comment]
多思考，多抽象，减少重复代码，让我们把更多的时间用于业务思考和个人成长上~

**Comment by leeory** [comment]
大神，你这个项目怎么集成log4j不用默认的logback做日志啊，弄了半天还是没弄出来啊

**Comment by lihengming** [comment]
@leeory https://blog.csdn.net/yucaifu1989/article/details/78647442
