### ISSUE TITLE
关于org.freemarker的冲突

### ISSUE THREAD

**Issue by 18068375397** [lihengming/spring-boot-api-project-seed#110]
您好，我fork了您的项目，可以自动生成，可是我发现如果我用了freemarker配置好后，一直抱没有指定view，我换成thymeleaf后页面可以正常过去，我注掉org.freemarker后就能正常跳转。所以springboot的freemarker是和他冲突吗？

**Comment by lihengming** [comment]
springboot 默认不支持 freemarker
