### ISSUE TITLE
restful遇到这样的问题，接口冲突怎么办

### ISSUE THREAD

**Issue by secutity** [lihengming/spring-boot-api-project-seed#112]
@GetMapping(value = "/person")
    public Result getAllPerson() {
        iService = new GetAllService();
        Object json = JSONObject.toJSON(iService.handler());
        return new Result(0, json, "");
    }
    @GetMapping(value = "/person")
    public Result getPersonByName(@RequestParam String name) {
        iService = new GetServiceByName();
        Object json = JSONObject.toJSON(iService.handler());
        return new Result(0, json, "");
    }

**Comment by lihengming** [comment]
。请确保Path是唯一的

**Comment by secutity** [comment]
我这样解决了，以前都没遇到过，在getmapping里有params这个参数，强制你添加参数才能访问这个接口
