### ISSUE TITLE
改动了ProjectConstant文件中的包名生成的项目结构有点蒙

### ISSUE THREAD

**Issue by cyixlq** [lihengming/spring-boot-api-project-seed#115]
![qq 20180417163221](https://user-images.githubusercontent.com/24880520/38857883-ed7dbbbe-425c-11e8-98d4-a3bad7aeca6c.png)
出现这样的问题，引入的东西报错。
![qq 20180417163457](https://user-images.githubusercontent.com/24880520/38858029-4d09cbcc-425d-11e8-879c-c1d8a5e49780.png)
所以是ProjectConstant文件中下面的常量应该进行一些相应的修改咯？

**Comment by lihengming** [comment]
把 com.company.project 直接改成你的包，然后再修改ProjectConstant里面的路径。
