### ISSUE TITLE
Logger logger 请问日志文件在哪里查看

### ISSUE THREAD

**Issue by delphishen** [lihengming/spring-boot-api-project-seed#119]
没找到配置日志路径的地方，请问在哪里查看日志文件？   是不是要配置？ 有没默认的

**Comment by lihengming** [comment]
日志需要配置的，默认只是在控制台打印，具体配置你搜一下很多教程，或者看官方文档。

**Comment by lihengming** [comment]
日志需要配置的，默认只是在控制台打印，具体配置你搜一下很多教程，或者看官方文档。
