### ISSUE TITLE
项目导入报错，可能跟版本相关

### ISSUE THREAD

**Issue by luoyimo** [lihengming/spring-boot-api-project-seed#12]
从github中复制下来之后，在intellij中多个类报错，全是注解不存在，有reimport

**Comment by lihengming** [comment]
@luoyimo 估计是Maven配置有问题，导致依赖的包没有下载下来。

**Comment by luoyimo** [comment]
应该是我maven的配置有问题  今天刚改过私服

**Comment by lihengming** [comment]
@luoyimo 你可以把你的settings.xml文件发过来，帮你看看。

**Comment by luoyimo** [comment]
没问题了  刚刚是忘记今天改过私服了。

**Comment by luoyimo** [comment]
方便的话  我想问一下接口验签不用mvc可以怎么做？

**Comment by lihengming** [comment]
@luoyimo 什么意思？

**Comment by luoyimo** [comment]
我需要做一个前后端完全分离的项目，对提供的接口请求验证，做登录限制之类的

**Comment by lihengming** [comment]
使用Sign签名认证或JWT，你可以看看这两篇文章：
-  [使用JWT确保API的安全](https://segmentfault.com/a/1190000007119872)
-  [JWT 在前后端分离中的应用与实践](http://www.open-open.com/lib/view/open1433995002942.html)

**Comment by luoyimo** [comment]
OK，非常感谢

**Comment by Jial08** [comment]
您好，我的也存在注解报错的问题，以下是我的settings.xml配置信息，应该没错啊，打开maven包的spring-web，注解打不开
![image](https://user-images.githubusercontent.com/25861104/27811859-1e34efae-609d-11e7-9dd1-616d7682b606.png)
劳烦您帮忙解决，感谢！
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                          https://maven.apache.org/xsd/settings-1.0.0.xsd">
  
  <localRepository>D:\maven\.m2\repository</localRepository>
  
  <mirrors>
	<mirror>
        <id>nexus-aliyun</id>
        <name>Nexus aliyun</name>
        <url>http://maven.aliyun.com/nexus/content/groups/public</url>
		<mirrorOf>*</mirrorOf>
    </mirror>
  </mirrors>
</settings>

**Comment by Jial08** [comment]
配置文件发上来走样了，补个图吧

![qq 20170704094607](https://user-images.githubusercontent.com/25861104/27811926-a1e17f3e-609d-11e7-8979-749959b01767.png)

**Comment by Jial08** [comment]
不好意思，问题已经解决了，可能以前下的jar包有问题，我把springframework文件夹下的jar包全删了然后用maven重新下了遍，好了。

**Comment by luoyimo** [comment]
大神  对lamda表达式熟悉吗

**Comment by luoyimo** [comment]
这段代码改成lamda表达式应该是什么样子
new RowMapper<DataMap>()
        {
            @Override
            public DataMap mapRow(ResultSet rs, int rowNum) throws SQLException
            {
                ResultSetMetaData metaData = rs.getMetaData();
                return toDataMap(rs, metaData);
            }
        });

**Comment by lihengming** [comment]
```java
  RowMapper rowMapper = (ResultSet rs, int rowNum) -> {
            ResultSetMetaData metaData = rs.getMetaData();
            return toDataMap(rs, metaData);
        };
```

**Comment by luoyimo** [comment]
豁然开朗  谢谢大神

**Comment by luoyimo** [comment]
mybatis查询能拿到未封装成对象之前的map吗
