### ISSUE TITLE
springboot单元测试特别慢  有什么好的方法吗

### ISSUE THREAD

**Issue by luoyimo** [lihengming/spring-boot-api-project-seed#123]

**Comment by lihengming** [comment]
主要是启动 Spring Context 比较慢，可以减少 Context 中 Bean的数量，比如你测试 AService，它只依赖 BService、CService，那你测试的之后只讲这3个Bean放入 Context 中即可。不用扫描所有的包将所有包中的 Bean 放入 Context 。

**Comment by luoyimo** [comment]
我用的注解，要在测试时删除注解吗

**Comment by lihengming** [comment]
我意思是你默认会加载所有Bean，你可以使用 `@ComponentScan` 减少加载Bean的数量，只加载你要单元测试的Bean和他所依赖的Bean，比如你要测试Service层那么你可以`@ComponentScan(basePackages = { "com.company.service" })  
`只加载这个包下面的Bean，以此类推，明白了吧？

**Comment by luoyimo** [comment]
好的
