### ISSUE TITLE
似乎Result class里面不需要用泛型吧 会有很有warning.

### ISSUE THREAD

**Issue by CTancy** [lihengming/spring-boot-api-project-seed#143]
似乎Result class里面不需要用泛型吧 会有很有warning.
warning类似result is a raw type. References to generic type Result<T> should be parameterized。
data的类型改为Object。 

这里用泛型有什么必要性？
![_124f0eb0-1c2d-4b3a-ac94-b0e7ee73a59f](https://user-images.githubusercontent.com/16119716/42434634-7c240dc2-8386-11e8-97d8-06e06fa7c2eb.png)

**Comment by lihengming** [comment]
泛型可以让代码更具可读性（知道 Result 里面放的到底是什么类型的数据），你也可以不声明类型呀，默认就是 Object，比如下面这两种用法。当然你也可以去掉泛型，没问题的。

```
 @PostMapping("/delete")
    public Result<User> delete(@RequestParam Integer id) {
        userService.deleteById(id);
        return ResultGenerator.genSuccessResult();
    }

    @PostMapping("/update")
    public Result update(User user) {
        userService.update(user);
        return ResultGenerator.genSuccessResult();
    }
```
