### ISSUE TITLE
请问如何注入额外的字段

### ISSUE THREAD

**Issue by ladmini** [lihengming/spring-boot-api-project-seed#159]
你好，我是一个iOS开发者，最近准备写一个小型的Java restful应用，看了您的框架，非常的简洁好用，我0基础也能很快的入门，感谢！！！我有一个小问题请教一下，假如我有这样的需求，除了返回数据库User表里面的所有的字段以外，我还需要额外返回一个当前服务器的时间戳，这个字段是只读的，我尝试把这个字段手动加到User这个Model里面，但是报错了，Unknown column 'current' in 'field list' 请问我应该怎么定义这个字段？ 非常感谢！

**Comment by javastar920905** [comment]
@Transient  标识在字段名上面可以


| |
T
|
|
javastar920905@163.com
|
签名由网易邮箱大师定制
在2018年8月29日 09:50，李竹 (Zhu Li)<notifications@github.com> 写道：

你好，我是一个iOS开发者，最近准备写一个小型的Java restful应用，看了您的框架，非常的简洁好用，我0基础也能很快的入门，感谢！！！我有一个小问题请教一下，假如我有这样的需求，除了返回数据库User表里面的所有的字段以外，我还需要额外返回一个当前服务器的时间戳，这个字段是只读的，我尝试把这个字段手动加到User这个Model里面，但是报错了，Unknown column 'current' in 'field list' 请问我应该怎么定义这个字段？ 非常感谢！

**Comment by ladmini** [comment]
@javastar920905 
amazing!!!  非常感谢!!!  太好用了
稍微更正一下是@Transient 我这边用首字母小写报错了。
