### ISSUE TITLE
状态码推荐使用spring的HttpStatus

### ISSUE THREAD

**Issue by jaune162** [lihengming/spring-boot-api-project-seed#16]
项目本身就是Web项目，已经包含了org.springframework.http.HttpStatus类，可以直接使用，而且状态非常全。没必要重新定义吧。

**Comment by lihengming** [comment]
响应码只是参考Http状态码，根据业务肯定还会自定义一些，所以就单独建了一个枚举类~ 当然啦，使用org.springframework.http.HttpStatus类，也是个不错的选择，根据自己的需求来调整吧~
