### ISSUE TITLE
我想修改生成的xml 请问哪里可以修改

### ISSUE THREAD

**Issue by sunchenxin98** [lihengming/spring-boot-api-project-seed#169]
我想修改生成的xml 请问哪里可以修改，代码里面找不到。就到找到4个ftl 是生成java的

**Comment by a173030685** [comment]
> 我想修改生成的xml 请问哪里可以修改，代码里面找不到。就到找到4个ftl 是生成java的

是不支持的吧

**Comment by sunchenxin98** [comment]
@a173030685  额 这就尴尬了...

**Comment by javastar920905** [comment]
持久层是用mybatis generator 或者通用mapper generator的 可以自定义generator相关的插件, 达到修改生成的Interface 和mapper.xml的目标   不过比较麻烦  


| |
T
|
|
javastar920905@163.com
|
签名由网易邮箱大师定制
在2018年10月15日 10:02，孙程心<notifications@github.com> 写道：

@a173030685 额 这就尴尬了...
