### ISSUE TITLE
建议添加enum枚举字段实例  这个与业务逻辑无关比较通用

### ISSUE THREAD

**Issue by DreamPWJ** [lihengming/spring-boot-api-project-seed#180]
建议添加enum枚举字段实例  这个与业务逻辑无关比较通用   比如状态 性别等等通用的枚举字段用例

**Comment by lihengming** [comment]
自行添加呗，这和框架没啥关系的。

**Comment by DreamPWJ** [comment]
已添加 但是mapper好像没有优雅的方式   只能一个枚举对应一个枚举处理器

**Comment by DreamPWJ** [comment]
@lihengming 重写枚举toString方法 设置WriteEnumUsingToString 生成的是字符串如何转换成json
![image](https://user-images.githubusercontent.com/16730031/50681493-abf18c80-1046-11e9-9bea-59f6cdd706ec.png)
如图 枚举类 是个字符串 如何自动转换成json 字符串前端还要单独处理 同时返回code和value是为了code用于判断 value用于直接显示 fastjson是在最后返回统一处理的 所以在之前单独处理无效

**Comment by DreamPWJ** [comment]
已解决上代码共享
![image](https://user-images.githubusercontent.com/16730031/50717162-61145b00-10c0-11e9-9177-8f1ef90b2a17.png)
![image](https://user-images.githubusercontent.com/16730031/50717207-97ea7100-10c0-11e9-8356-200d896b0e05.png)
