### ISSUE TITLE
druid-spring-boot-starter无法读取yml配置信息

### ISSUE THREAD

**Issue by chillzhuang** [lihengming/spring-boot-api-project-seed#23]
DruidDataSourceAutoConfigure的dataSource用到了Environment,只能读取properties，没法读取yml

**Comment by lihengming** [comment]
@chillzhuang Environment 是对所有配置文件的抽象怎么可能没法读取yml呢，你去看看Spring官方问题，或者截图给出证据。

**Comment by chillzhuang** [comment]
抱歉，是我搞错了
