### ISSUE TITLE
这个东西 在mac 上使用有问题。

### ISSUE THREAD

**Issue by xiaoheiai4719** [lihengming/spring-boot-api-project-seed#3]
希望大哥 能把兼容做一下。service 生成的是空的

**Comment by lihengming** [comment]
@xiaoheiai4719 我没有Mac:sob: 没法测试，所以只考虑了Windows环境，我估计是分隔符的问题，你可以把路径中的\\换成/或使用``` File.separator```看看。

**Comment by lihengming** [comment]
@xiaoheiai4719 如果是```System.getProperty("user.dir")```的原因，可以将PROJECT_PATH写死，你测试完将结果告诉我。

**Comment by xiaoheiai4719** [comment]
大哥 给我 你微信？

**Comment by lihengming** [comment]
@xiaoheiai4719 89921218

**Comment by JaxXu** [comment]
提PR更方便吧

**Comment by lihengming** [comment]
代码生成器的文件分隔符从\\换成/了，不影响Windows下的使用（[详情见Stackoverflow Question](https://stackoverflow.com/questions/4845866/java-on-windows-prevent-slash-in-file-name-from-acting-as-a-separator)），我觉得使用```File.separator```拼接字符串太丑了，就没用，其实最好用这个。
