### ISSUE TITLE
Could not autowire. There is more than one bean of 'DataSource' type.

### ISSUE THREAD

**Issue by wenqibo** [lihengming/spring-boot-api-project-seed#31]
在Mybatis & Mapper & PageHelper 配置类 MybatisConfigurer 里面，29行有一个报错：
![qq 20170721115808](https://user-images.githubusercontent.com/4066180/28448634-037da706-6e0c-11e7-9e5b-95f5268435d8.png)

Could not autowire. There is more than one bean of 'DataSource' type.
Beans:
dataSource   (DataSourceConfiguration.class) dataSource   (DataSourceConfiguration.class) 
less... (Ctrl+F1) 
Checks autowiring problems in a bean class.

环境
Intellij Ide 2017.2
 jdk1.8

**Comment by lihengming** [comment]
@wenqibo Hi，这不是报错啦，是IDE的温馨提示而已，不用理会。

它就是告诉你没有发现定义了DataSouce类型的Bean，可能会注入失败（其实不会的，在启动时会自定配置创建数据源的），这提示和在Service内注入Mapper接口的提示一样，Mapper接口在Spring上下文启动时才会生成实现类，而IDE不知道。

你可以将这个提示改为```warn```级别，步骤如下（IntelliJ IDEA）

![](https://raw.githubusercontent.com/lihengming/java-codes/master/shared-resources/github-images/issue-31/step1.png)
![](https://raw.githubusercontent.com/lihengming/java-codes/master/shared-resources/github-images/issue-31/step2.png)

**Comment by wenqibo** [comment]
好的，谢谢

**Comment by wenqibo** [comment]
@lihengming 能否这样写呢：
    public SqlSessionFactory sqlSessionFactoryBean(@Qualifier("dataSource") DataSource dataSource) throws Exception {
加一个Qualifier修饰符

**Comment by lihengming** [comment]
可以，如果有多个数据源的话，可以用它来指定要注入的是哪个数据源，不过目前就一个数据源，加上没有任何实际意义。

**Comment by wenqibo** [comment]
@lihengming 好的。

**Comment by SuperZhouyong** [comment]
楼主，这个多个数据源，有demo吗。初次写后台，不是很会
