### ISSUE TITLE
用户只能操作他自己的资源

### ISSUE THREAD

**Issue by huanzhang** [lihengming/spring-boot-api-project-seed#34]
@lihengming 怎么做用户权限验证？

**Comment by lihengming** [comment]
什么意思呢？Shiro 吗？

**Comment by huanzhang** [comment]
@lihengming 嗯

**Comment by lihengming** [comment]
这个问题一时半会也说不清，看看下面这两篇文章吧
- 跟着开涛学 Shiro：http://jinnianshilongnian.iteye.com/blog/2018936
- Spring Boot 集成Shiro：http://blog.csdn.net/catoop/article/details/50520958

**Comment by huanzhang** [comment]
多谢
