### ISSUE TITLE
你这个支持添加乐观锁插件么

### ISSUE THREAD

**Issue by pandboy** [lihengming/spring-boot-api-project-seed#43]
处理并发数据问题，需要添加乐观锁，你这个没有啊，需要的话这个通用Mapper是怎么添加的。

**Comment by lihengming** [comment]
不好意思，最近比较忙，没看到，MyBatisb通用Mapper插件应该支持的，你可以去它们的官方文档或者GitHub提一个Issue问一下，: )。
- 文档地址：https://mapperhelper.github.io/docs/
- GitHub地址：https://github.com/abel533/Mapper
