### ISSUE TITLE
insertSelective如何返回主键ID？

### ISSUE THREAD

**Issue by tracyxs** [lihengming/spring-boot-api-project-seed#46]
用的oracle数据库，配置了ID是从sequence生成的，如下。
![image](https://user-images.githubusercontent.com/30264127/29864732-2a90db42-8da6-11e7-9368-e99c5e323a89.png)
目前插入正常，返回值是1，应该是记录数。
如果需要返回生成的ID，能支持吗，应该怎么配置？

**Comment by lihengming** [comment]
这是MyBastis默认的，返回的都是记录数。你要取的主键的话，插入成功后直接从Model对象取就可以了，会自动注入回来的。
```java
User user = new User();
user.setName(“土豆”);
userMapper.insertSelective(user);
user.getId();//即可
```

**Comment by bdyz1016** [comment]
插入后没有注入回来
` @GeneratedValue(generator = "uuid")`
