### ISSUE TITLE
Controller 中制造个异常 如何让service中的操作 也能回滚

### ISSUE THREAD

**Issue by sniperZj** [lihengming/spring-boot-api-project-seed#51]
@RestController
@RequestMapping("/person")
public class PersonController {
 @Resource
    private PersonService personService;

    @PostMapping("/add")
    public Result add(Person person) {
        personService.save(person);
        System.out.println(1/0);
        return ResultGenerator.genSuccessResult();
    }
}

public interface PersonService extends Service<Person> {

}

@Service
@Transactional
public class PersonServiceImpl extends AbstractService<Person> implements PersonService {

}

**Comment by sniperZj** [comment]
@Service
@Transactional
public class PersonServiceImpl extends AbstractService<Person> implements PersonService {

  @Override
  public void test(Person person){
    save(person);
    System.out.println(1/0);
  }
}
public interface PersonService extends Service {
void test(Person person);
}
 @PostMapping("/add")
    public Result add(Person person) {
            personService.test(person);
          return ResultGenerator.genSuccessResult();

    }
这种写法 是有效的

**Comment by lihengming** [comment]
事务是在Service层，你这异常是在Controller里面，当然不回滚了，除非你给Controller也加上事务，不过这是不建议的。
