### ISSUE TITLE
有多个表，生成好代码后，启动失败的问题

### ISSUE THREAD

**Issue by xiaozhu350** [lihengming/spring-boot-api-project-seed#53]
No qualifying bean of type 'com.xxx.core.Mapper<?>' available: expected single matching bean but found 2: citiesMapper,storesMapper

请问下这个如何解决？

**Comment by lihengming** [comment]
你这俩Mapper接口泛型里面是同一个Model是不行的，注入的时候会失败。

**Comment by lihengming** [comment]
一个表，一个Model，只能对应一个Mapper

**Comment by xiaozhu350** [comment]
public interface CitiesMapper extends Mapper<Cities> 
public interface StoresMapper extends Mapper<Stores>
我的泛型里面对应了不同的model啊，每个表都是单独生成的model类

**Comment by lihengming** [comment]
问题解决了么
