### ISSUE TITLE
pagehelper 和mapper 都有相应的spring boot starter，为什么没有使用它们呢？

### ISSUE THREAD

**Issue by xhusky** [lihengming/spring-boot-api-project-seed#55]
前段时间发现了这个问题，自己采用相应的starter测试了一下，没有发现什么问题，但是实际项目中还没有用到，所以无法确认是否有其他限制，可否说一下没有采用相应starter的意图和存在的限制么？多谢

**Comment by lihengming** [comment]
想法是这样的，为了简化配置，让涉及包名、路径相关的配置集中在```ProjectConstant```中，这样代码生成器和```MybatisConfigurer```相关配置就可以集中管理了，如果使用Starter的话MyBatis相关配置还需去配置文件中再配置一遍，大家感觉麻烦就不会用了（特别是对于新手来说），一个开源产品最重要的一点是无脑、简单，得让新手一看就会用。

**Comment by lihengming** [comment]
改成Starter也是没问题的，这套框架还是比较基础、精简的，就是为了方便大家去根据实际项目需求去调整。

**Comment by xhusky** [comment]
@lihengming 好的，多谢，以为会有什么限制才问了一下
