### ISSUE TITLE
怎么运行 CodeGenerator.main() 阿？

### ISSUE THREAD

**Issue by delphiboy1980** [lihengming/spring-boot-api-project-seed#59]
在Intellij IDEA里面运行的时候，会出现如下错误：
错误: 找不到或无法加载主类 CodeGenerator

我是新手，求指教

**Comment by lihengming** [comment]
执行CodeGenerator类的main方式啊~

**Comment by delphiboy1980** [comment]
执行的时候就提示这个错误了 

> 错误: 找不到或无法加载主类 CodeGenerator

我是不是有什么东西没有配好？

**Comment by FCcoder** [comment]
你需要先执行maven的build，然后运行主类就可以了。

**Comment by benling** [comment]
main方法执行报错？
![default](https://user-images.githubusercontent.com/3862952/40357212-025ae67c-5dee-11e8-8889-b795f2a9c569.png)

**Comment by benling** [comment]
表名不能输入多个？类似：user,city,employe，只能一个个输入。

**Comment by lihengming** [comment]
可以啊，本来就是一个可变参数。
