### ISSUE TITLE
小建议

### ISSUE THREAD

**Issue by CoolCoderTony** [lihengming/spring-boot-api-project-seed#6]
spring boot这种简洁代码和lombok更配哦！

**Comment by lihengming** [comment]
@CoolCoderTony  哈哈 使用Lombok代码确实看着很赏心悦目，不过代码都是生成的就没那个必要啦，锦上添花的东东，根据自己口味来添加吧:smile:

**Comment by DreamPWJ** [comment]
强烈建议lombok    每次生成model都要去清楚get set方法  数据库自动频繁改动  lombok方式维护起来更方便

**Comment by DreamPWJ** [comment]
MyBatis Generator生成器 自动生成lombok选项

**Comment by DreamPWJ** [comment]
配置代码生成  需要版本Mapper 4.1.0
  pluginConfiguration.addProperty("lombok", "Getter,Setter,ToString");
