### ISSUE TITLE
反馈一下dome-user.sql 

### ISSUE THREAD

**Issue by sunchenxin98** [lihengming/spring-boot-api-project-seed#60]
在mysql 5.6
执行sql会报错
错误代码： 1294
Invalid ON UPDATE clause for 'register_date' column

把
 `register_date` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
替换为
`register_date` DATETIME NOT NULL,
即可

**Comment by lihengming** [comment]
好的，我改一下~
