### ISSUE TITLE
为什么生成的代码post请求json格式Integer类型参数读取失败

### ISSUE THREAD

**Issue by zheng-zy** [lihengming/spring-boot-api-project-seed#7]
post detail json 格式{"id":1} controller参数id获取null

**Comment by lihengming** [comment]
Spring MVC 请求参数默认接收的是application/x-www-form-urlencoded类型的，如果你要接受application/json类型的参数需要在参数前添加@RequestBody注解。

**Comment by JhonwillBao** [comment]
求不乱发，有点吵，谢谢体谅




------------------ 原始邮件 ------------------
发件人: "土豆";<notifications@github.com>;
发送时间: 2017年7月3日(星期一) 中午11:12
收件人: "lihengming/spring-boot-api-project-seed"<spring-boot-api-project-seed@noreply.github.com>; 
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: Re: [lihengming/spring-boot-api-project-seed] 为什么生成的代码post请求json格式Integer类型参数读取失败 (#7)




Spring MVC 请求参数默认接收的是application/x-www-form-urlencoded类型的，如果你要接受application/json类型的参数需要在参数前添加@requestbody注解。

**Comment by lihengming** [comment]
@JhonwillBao 不是我给你发的，你点击右上角的Unwatch，GitHub就不会给你发了。

**Comment by zheng-zy** [comment]
3q




zhezhiyong

发件人： 土豆
发送时间： 2017-07-03 11:12
收件人： lihengming/spring-boot-api-project-seed
抄送： 苏陌年; Author
主题： Re: [lihengming/spring-boot-api-project-seed] 为什么生成的代码post请求json格式Integer类型参数读取失败 (#7)
Spring MVC 请求参数默认接收的是application/x-www-form-urlencoded类型的，如果你要接受application/json类型的参数需要在参数前添加@requestbody注解。

**Comment by JhonwillBao** [comment]
哦哦，不好意思，忘了点过watch= =。






------------------ 原始邮件 ------------------
发件人: "土豆";<notifications@github.com>;
发送时间: 2017年7月3日(星期一) 中午11:17
收件人: "lihengming/spring-boot-api-project-seed"<spring-boot-api-project-seed@noreply.github.com>; 
抄送: "包健慧"<564447468@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [lihengming/spring-boot-api-project-seed] 为什么生成的代码post请求json格式Integer类型参数读取失败 (#7)




@JhonwillBao 不是我给你发的，你点击右上角的Unwatch，GitHub就不会给你发了。
