### ISSUE TITLE
有没有大神能写个更新了表结构更新model的代码生成工具

### ISSUE THREAD

**Issue by wirechen** [lihengming/spring-boot-api-project-seed#72]
我觉得这个还是比较实用吧

**Comment by lihengming** [comment]
重新生成下不就好了..

**Comment by wirechen** [comment]
:） ok 我傻逼了~~ 但是重新生成如果写了controller和service不久被覆盖了？好吧，可以把生成model的代码单独提出来，我还是傻逼了~ 关了关了，免得让别人笑话😆
