### ISSUE TITLE
请问签名认证请求发送之前的sign如何生成

### ISSUE THREAD

**Issue by ldw4033** [lihengming/spring-boot-api-project-seed#8]
你好。我想请教一下：http://localhost:8080/sys/user/?page=1&size=10&sign=XXX 每次请求发出之前都要对sign进行生成，由于每次请求不同的参数生成的sign也会不一样的，那这个 工作是在前端生成的sign吗？这样的话，生成签名的密钥 String secret = "Potato";是不是就要暴露在前端啊。还是有其他方法啊

**Comment by lihengming** [comment]
没办法，确实是这样的  安卓 IOS这种编译语言还好，对于前端JS调用推荐使用JSON Web Token，不过其实都没用，JS是解释型语言，别人真要恶意调用，防不住的，只能增加恶意调用的成本吧。

**Comment by vectooor** [comment]
对于浏览器端的调用，目前的方式就是使用jwt来解决。对于非浏览器调用，例如一个C/S架构的客户端接入，那么，客户端需要配置一个secret，这个secret客户端才知道，别人是不知道的，所以服务端可以保证请求来自可信任方，如果secret泄露了，那就没办法了。
