### ISSUE TITLE
AbstractService.java类中的@Autowired注解

### ISSUE THREAD

**Issue by salmon002** [lihengming/spring-boot-api-project-seed#81]
@Autowired
protected Mapper<T> mapper;

这段代码最终注入的是org.apache.ibatis.binding.MapperProxy实例， 可否帮忙解释下为什么不是Mapper接口的实现类（比如： UsersMapper）
谢谢

**Comment by lihengming** [comment]
MapperProxy 就是对应 Mapper 的实现类，UsersMapper 也是接口啊，MyBatis 通过解析 XML 生成代理类来实现 UsersMapper。

**Comment by lihengming** [comment]
可以Debug或看下 org.apache.ibatis.binding.MapperProxyFactory 的源码你就知道了

**Comment by salmon002** [comment]
Spring小白受教了，谢谢
