### ISSUE TITLE
新手，想问下怎么将工程导入，用as还是myeclipse，不会导入

### ISSUE THREAD

**Issue by StarShine761** [lihengming/spring-boot-api-project-seed#82]

**Comment by xzm1102207843** [comment]
IntelliJ IDEA 你值得拥有 我是学Android滴  自学1个来月java, 替博主回答这个问题

**Comment by lihengming** [comment]
都可以的（推荐用 IntelliJ IDEA），只要支持Maven项目就行 ，你把项目克隆下来，用IDE打开项目目录就可以了，也可以通过IDE内的图形界面直接输入项目的git地址导入。

**Comment by StarShine761** [comment]
感谢大佬，好久没有做Java了，
