### ISSUE TITLE
在接口里如何getRequest().getReader(); ? 只能传入参数,如果是流数据,要怎么传入?

### ISSUE THREAD

**Issue by gclsoft** [lihengming/spring-boot-api-project-seed#85]
```
   /**
     * 微信支付成功的回调接口
     * @return
     */
    @PostMapping("/paynotify")
    public String paynotify() {
        StringBuilder sb = new StringBuilder();
        BufferedReader in;
        try {
            in = getRequest().getReader();
            String line;
            while ((line = in.readLine()) != null) {
                sb.append(line);
            }
```
只能传入参数,如果是流数据,要怎么传入?

**Comment by lihengming** [comment]
什么意思

**Comment by gclsoft** [comment]
```
    @PostMapping("/paynotify2")
    public String paynotify2(HttpServletRequest request) {
        return "success";
    }
```
@lihengming 已经解决,传入HttpServletRequest request参数就可以. 现在返回"success"微信支付接收到的是带双引号的"success", 不符合它不需要双引号的标准,会重发三次, 要怎么只返回success?
试了下面的都不行:
    String strRet=JSON.toJSONString("success", SerializerFeature.WriteNonStringKeyAsString);
        logger.info("notify:"+strRet);
        return strRet;

**Comment by gclsoft** [comment]
![image](https://user-images.githubusercontent.com/1269898/35030007-78d658ee-fb98-11e7-9b60-69989e27632e.png)
