### ISSUE TITLE
使用/add方法的时候无法写入MYSQL，因为传过来的datetime是String

### ISSUE THREAD

**Issue by g527727372** [lihengming/spring-boot-api-project-seed#86]
我应该在哪个位置把JSON转为对象呢？在control里重新写add是可以，重新定义一个UserType，然后把它类型转成User，在save。
请问这样是正确的修改姿势吗？

**Comment by lihengming** [comment]
`@RequestBody `注解会自动将JSON转换为Model的，日期类型直接传long类型的时间戳
