### ISSUE TITLE
想在生成的model的字段加上数据库表结构的字段注释，但是我自己实现的注释类被覆盖掉了，有什么好的解决办法

### ISSUE THREAD

**Issue by seeingme** [lihengming/spring-boot-api-project-seed#97]
PluginConfiguration pluginConfiguration = new PluginConfiguration();
pluginConfiguration.setConfigurationType("tk.mybatis.mapper.generator.MapperPlugin");
pluginConfiguration.addProperty("mappers", MAPPER_INTERFACE_REFERENCE);
 context.addPluginConfiguration(pluginConfiguration);
好像是这个插件配置的原因

**Comment by lihengming** [comment]
看下文档吧，中文的：https://blog.csdn.net/poisions/article/details/51119386
